[package]
name = "jisp_sha2_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jisp_sha2 = {path = "../jisp_sha2" }
eframe = "0.27.2"